apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io/
    targetRevision: v1.8.0
    helm:
      values: |
        preUpgradeChecker:
          jobEnabled: false
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

