apiVersion: apps/v1
kind: Deployment
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: longhorn
  template:
    metadata:
      labels:
        app: longhorn
    spec:
      containers:
      - name: longhorn-manager
        image: longhornio/longhorn-manager:v1.2.3
        ports:
        - containerPort: 9500

