releases:
  - name: {{ .Values.chart }}
    namespace: argocd
    chart: {{ .Values.chart }}
    disableValidation: true
    hooks:
      - events: ["prepare"]
        command: mkdir
        args:
          - -p
          - "{{ .Values.chart }}/manifests"
      - events: ["prepare"]
        command: bash
        args:
          - -c
          - |
            # Ensure the manifests folder exists before writing
            mkdir -p manifests
            cat <<EOF > manifests/application.yaml
            apiVersion: argoproj.io/v1alpha1
             kind: Application
             metadata:
               name: {{ .Values.chart }}
               namespace: argocd
             spec:
               project: default
               syncPolicy:
                 syncOptions:
                   - CreateNamespace=true
               source:
                 repoURL: '{{ .Values.repoURL }}'
                 chart: '{{ .Values.chart }}'
                 targetRevision: '{{ .Values.targetRevision }}'
                 helm:
                   valuesFiles:
                     - values.yaml
               destination:
                 server: https://kubernetes.default.svc
                 namespace: {{ .Values.namespace }}
             EOF
