apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeblocks
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rahulkreddy67/argocd
    targetRevision: HEAD
    path: argocd/kubeblocks
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeblocks-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
