name: Helmfile Render
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
  pull_request:
    branches:
      - main
jobs:
  helmfile-render:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v2
      # Set up Helm and Helmfile
      - name: Install Helm and Helmfile
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          curl -Lo helmfile https://github.com/helmfile/helmfile/releases/download/v0.170.0/helmfile_linux_amd64
          chmod +x helmfile
          sudo mv helmfile /usr/local/bin/
      # Install yq for parsing values.yaml
      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y yq
      # Render Helmfile for all apps
      - name: Render all apps
        run: |
          for dir in */; do
            echo "Rendering Helmfile in $dir"
            mkdir -p "$dir/manifests"
            helmfile -f "$dir/helmfile.yaml" template > "$dir/manifests/application.yaml"
          done

      - name: Commit rendered manifests
        run: |
          git add "$dir/output/application.yaml"
          git commit -m "Update application.yaml for $(basename $dir)"
          git push origin HEAD
        continue-on-error: true
